name: Compilar Mod Voidborn

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Baixar repositorio
        uses: actions/checkout@v4


      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Extrair ZIP do projeto
        run: |
          mkdir projeto

          unzip -o *.zip -d projeto

          echo "Arquivos encontrados:"
          find projeto -name "build.gradle"
          find projeto -name "gradlew"


      - name: Encontrar projeto Forge
        run: |
          BUILD=$(find projeto -name "build.gradle" | head -n 1)

          if [ -z "$BUILD" ]; then
            echo "Nenhum build.gradle encontrado"
            exit 1
          fi

          DIR=$(dirname "$BUILD")

          echo "Projeto encontrado em:"
          echo "$DIR"

          echo "PROJECT_DIR=$DIR" >> $GITHUB_ENV


      - name: Dar permissão ao Gradle
        run: |
          chmod +x "$PROJECT_DIR/gradlew"


      - name: Compilar Mod
        run: |
          cd "$PROJECT_DIR"
          ./gradlew build -x test --no-daemon


      - name: Enviar JAR
        uses: actions/upload-artifact@v4
        with:
          name: Voidborn-Mod-JAR
          path: "**/build/libs/*.jar"
