name: Compilar Mod Voidborn

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permissao no Gradlew
        run: chmod +x gradlew

      - name: Traduzir .java para .class e gerar .jar
        run: ./gradlew build

      - name: Enviar arquivo .jar pronto
        uses: actions/upload-artifact@v4
        with:
          name: Voidborn-Mod-JAR
          path: build/libs/*.jar
